# Generated by Django 3.2.9 on 2021-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='room_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(max_length=100),
        ),
    ]
