# Generated by Django 3.2.9 on 2021-12-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20211205_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.URLField(),
        ),
    ]
