# Generated by Django 3.2.9 on 2021-12-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_song_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uri',
            field=models.CharField(max_length=100),
        ),
    ]
